### ISSUE TITLE
Why is it not working ? what am i doing wrong?

### ISSUE THREAD

**Issue by HasanY1989** [scottstamp/PokemonGo-Map#26]
Hey ya all
I have no idea what i'm doing wrong. 
On the easy setup, it gives me this error. 
"Command "python setup.py egg_info" failed with error code 1 in c:\users\haso\appdata\local\temp\pip-build-k4z4cl\pyproj\"
after that i try to do npm install. 
works fine but when i run it, it gives me this error. 

Traceback (most recent call last):
  "File "runserver.py", line 28, in <module>
    import pgoapi
  File "C:\Python27\lib\site-packages\pgoapi-1.1.6-py2.7.egg\pgoapi__init__.py", line 1
SyntaxError: Non-ASCII character '\xf3' in file C:\Python27\lib\site-packages\pgoapi-1.1.6-py2.7.egg\pgoapi__init__.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details"

i run ith with cmd line: 

C:\Python27\Python.exe runserver.py -a ptc -u user-u use -u user -p pas2 -p pas3 -p pass4 -l "NewYork,America" -st 8 -sd 5 -H 0.0.0.0 -L en -P 69

**Comment by HasanY1989** [comment]
please help !
im losing my mind, i do not understand what im doing wrong !!!

**Comment by Azryyal** [comment]
See #4 #5 and pull request #10

**Comment by HasanY1989** [comment]
Fixed ty
