### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in \temp\pip-build-merbvz\xxhash\

### ISSUE THREAD

**Issue by PeshBG** [scottstamp/PokemonGo-Map#28]
I am trying to install it on a laptop(i managed to do it today on my home pc) 
i follow the same instructions but i continue to get the error... any ideas?

i follow those : 

Download Git for Windows here and install it.

Download Microsoft Visual C++ Compiler for Python 2.7 here

Download Python 2 (latest 2.7.12) here and install it. When installing check that the python location gets appended to the PATH enviroment variable!

Then download pip (right click that link and choose "Save Link As"), and double click the file you downloaded, assuming you installed Python correctly.

Download NodeJS (latest 6.3.1) here and install.

Open a git bash on your PokemonGo-Map folder with mouse's right click -> Git Bash Here

Launch

pip install -r requirements.txt

**Comment by PeshBG** [comment]
the script couldnt connect to the nose repository...

**Comment by EvolvedPie** [comment]
How did you fix the problem though?
