### ISSUE TITLE
python setup.py egg_info

### ISSUE THREAD

**Issue by EvolvedPie** [scottstamp/PokemonGo-Map#30]
Running on Windows.
I've installed Git, Python and pip.
When I run the command: pip2.7.exe install -r requirements.txt 
I get the error:
Command "python setup.py egg_info" failed with error code 1 in c:\users\alistair\appdata\local\temp\pip-build-vexjau\pyproj\

According to issue #28 it is because the script couldn't connect to the nose repository.
But how do you fix this issue?

Many thanks

**Comment by IHG54** [comment]
Hi ,
I search for a solution this morning :(

**Comment by 7ESL4** [comment]
Read the line before the error.  It should tell you what you need to do.

**Comment by Azryyal** [comment]
This is a duplicate of #5 and solved with pull request #10 ... you need to download MS VC for python.

**Comment by EvolvedPie** [comment]
That solved it.  Thanks a lot for the help.
