### ISSUE TITLE
Error running setup.bat

### ISSUE THREAD

**Issue by 7ESL4** [scottstamp/PokemonGo-Map#32]
When running setup, I get 2 errors.  Both are in reference to:

Cloning git://github.com/keyphact/pgoapi.git to C:......  causing the folder \src to be empty (after deleting the document called "delete me"
## Expected Behavior

Cloning git://github.com/keyphact/pgoapi.git should clone to folder.
## Current Behavior

Folder remains empty.
## Possible Solution

I may not have properly installed POGOProtos, but there is no clear documentation on it.
## Your Environment

Windows 10
Python 2.7

**Comment by Cammo009** [comment]
Run it using Git Bash and not Cmd

**Comment by 7ESL4** [comment]
Sorry, I'm kind of a noob.  What is Git Bash?

**Comment by 7ESL4** [comment]
Now I'm getting the error that says:

Command "python setup.py egg_info" failed with error code 1 in c:\temp\pip-euilb-o_j00m\pyproj\

Downloading Visual C++ 9.  Will test and update or close.

**Comment by 7ESL4** [comment]
Updated Visual C++ 9 per instructions.  Issue Solved.
