### ISSUE TITLE
Cannot Run the local server

### ISSUE THREAD

**Issue by A5LAN** [scottstamp/PokemonGo-Map#42]
It asks me to install the requirements.txt but when I do I receive this 
![image](https://cloud.githubusercontent.com/assets/8560891/17528148/2bcda57a-5e3c-11e6-8dcf-769b86028445.png)

Since I had seen that I thought it was all good to go so when I try to run the server this pops up

![image](https://cloud.githubusercontent.com/assets/8560891/17528200/578f712a-5e3c-11e6-9eb4-f492686fa706.png)
## Your Environment

Windows 10 Asus Laptop Python 2.7

**Comment by Azryyal** [comment]
Run the get-pip script to get pip. Then run the pip that is installed
in your python27/scripts directory.

On 8/9/16, Okan Dodanli notifications@github.com wrote:

> It asks me to install the requirements.txt but when I do I receive this
> ![image](https://cloud.githubusercontent.com/assets/8560891/17528148/2bcda57a-5e3c-11e6-8dcf-769b86028445.png)
> 
> Since I had seen that I thought it was all good to go so when I try to run
> the server this pops up
> 
> ![image](https://cloud.githubusercontent.com/assets/8560891/17528200/578f712a-5e3c-11e6-9eb4-f492686fa706.png)
> 
> ## Your Environment
> 
> Windows 10 Asus Laptop Python 2.7
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/scottstamp/PokemonGo-Map/issues/42

## 

a guy named Stacey

**Comment by A5LAN** [comment]
OH, wow I cant believe I forgot about that simple step thanks a bunch :D
