### ISSUE TITLE
Error 126 The Specified module cannot be found

### ISSUE THREAD

**Issue by A5LAN** [scottstamp/PokemonGo-Map#43]
## Expected Behavior

The local server should be up and running
## Current Behavior

Giving an error as seen by the picture below
![image](https://cloud.githubusercontent.com/assets/8560891/17534445/36ec982e-5e57-11e6-84bf-d9d7c4528ca3.png)
## Context

Because of this error I cannot scan the location but the server does run but the map can't scan.
## Your Environment

Python 2.7 
![image](https://cloud.githubusercontent.com/assets/8560891/17534534/9c4ed010-5e57-11e6-98a5-e52264f28b09.png)

**Comment by Azryyal** [comment]
Did you update line 271 (?) or search.py where the hardcoded path to
libencrypt.so is? And since you are on a Windows box, change that to
the path to encrypt.dll?

On 8/9/16, Okan Dodanli notifications@github.com wrote:

> ## Expected Behavior
> 
> The local server should be up and running
> 
> ## Current Behavior
> 
> Giving an error as seen by the picture below
> ![image](https://cloud.githubusercontent.com/assets/8560891/17534445/36ec982e-5e57-11e6-84bf-d9d7c4528ca3.png)
> 
> ## Context
> 
> Because of this error I cannot scan the location but the server does run but
> the map can't scan.
> 
> ## Your Environment
> 
> Python 2.7
> ![image](https://cloud.githubusercontent.com/assets/8560891/17534534/9c4ed010-5e57-11e6-98a5-e52264f28b09.png)
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/scottstamp/PokemonGo-Map/issues/43

## 

a guy named Stacey

**Comment by A5LAN** [comment]
@Azryyal  is this the correct method 
![image](https://cloud.githubusercontent.com/assets/8560891/17535697/265a1214-5e5e-11e6-905d-d2a78a2c0411.png)

**Comment by A5LAN** [comment]
I FIXED IT :D eyyyyy thanks so much
