### ISSUE TITLE
unexpected keyword argument 'proxy'

### ISSUE THREAD

**Issue by northfoxz** [scottstamp/PokemonGo-Map#47]
## Expected Behavior

It should be up and running
## Possible Solution

Exception in search_worker: perform_master_login() got an unexpected keyword argument 'proxy'.
## Steps to Reproduce (for bugs)
1. install and get running in ubuntu desktop 14.04
2. get error message "Exception in search_worker: perform_master_login() got an unexpected keyword argument 'proxy'."
## Your Environment
- Version used:
- Python 2.7.12
- Ubuntu Desktop 14.04

**Comment by Jieiku** [comment]
did you figure this out? I have the exact same error.

**Comment by Azryyal** [comment]
I don't think development is being done on this fork any more. You
should check out https://github.com/PokemonGoMap/PokemonGo-Map

On 8/30/16, xekon notifications@github.com wrote:

> did you figure this out? I have the exact same error.
> 
> ## 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/scottstamp/PokemonGo-Map/issues/47#issuecomment-243558570

## 

a guy named Stacey
