### ISSUE TITLE
Exception while processing libencrypt.so

### ISSUE THREAD

**Issue by nkcheng255** [scottstamp/PokemonGo-Map#7]
## Current Behavior

Exception while downloading map: dlopen(/root/PoGoMap/pogom/libencrypt.so, 6): no suitable image found.  Did find:
    /root/PoGoMap/pogom/libencrypt.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
## Steps to Reproduce (for bugs)

run python runserver.py
- Version used:
- Environment name and version (e.g. Python 2.7): Python 2.7.9 
- Operating System and version (desktop or mobile): OSX El Capitan

**Comment by imynwulf** [comment]
The usage of this encluded libencrypt depends on the distribution of linux that was used to compile it. 
You'll need to compile the library for OS X from source, then replace the included version with that.

**Comment by DragoonZ** [comment]
how can I compile it by myself?

**Comment by nkcheng255** [comment]
1. get the encrypt.c file
2. run this command in your terminal: gcc -shared -o libencrypt.so -fPIC encrypt.c

**Comment by DragoonZ** [comment]
@desource90 where can I find the encrypt.c file?

**Comment by imynwulf** [comment]
@DragoonZ Do a little bit of digging around. It's not that hard to track down.

**Comment by nkcheng255** [comment]
@imynwulf Thanks for the pointer. It works now.
